version: '3.0'

services:
  main:
    container_name: test
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run dev
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      DB_PORT: 3306
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

volumes:
  mysqldata: