name: CI build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  checkout_code:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload code as artifact
      uses: actions/upload-artifact@v3
      with:
        name: repository-files
        path: . 

  deploy_docker:
    name: Deploy to Docker on EC2
    runs-on: ubuntu-latest
    needs: checkout_code  

    steps:
    - name: Download repository files
      uses: actions/download-artifact@v3
      with:
        name: repository-files

    - name: Copy .env file to EC2 using SSM
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: |
          echo "PORT=5000" > .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env

    - name: Stop container
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: |
          docker stop test || true

    - name: Rm container
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: |
          docker rm test || true
      
    - name: Rebuild image
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        working-directory: /home/ubuntu/URL-shortener
        commands: |
          docker-compose build --no-cache
        
    
    - name: Rebuild container
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        working-directory: /home/ubuntu/URL-shortener
        commands: |
          docker-compose up -d

    - name: Debug Docker containers
      run: docker ps -a

  verify_deploy:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: deploy_docker 

    steps:
    - name: Verify Deployment
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
          if [ "$STATUS" -eq 200 ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
            exit 1
          fi

