name: CI build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  checkout_code:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload code as artifact
      uses: actions/upload-artifact@v3
      with:
        name: repository-files
        path: . 

  deploy_docker:
    name: Deploy to Docker on EC2
    runs-on: ubuntu-latest
    needs: checkout_code  

    steps:
    - name: Download repository files
      uses: actions/download-artifact@v3
      with:
        name: repository-files

    - name: Create .env file
      run: |
        echo "PORT=5000" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=3306" >> .env
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "REDIS_HOST=redis" >> .env
        echo "REDIS_PORT=6379" >> .env

    - name: Send command via SSM
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        document-name: "AWS-RunShellScript"
        commands: |
          aws s3 cp s3://$S3_BUCKET/test.tar.gz ~/test.tar.gz
          docker stop test || true
          docker rm test || true
          docker rmi url-shortener_main || true
          docker build --no-cache -t url-shortener_main -f ./Dockerfile .
          docker run -d --name test --env-file ~/app/.env -p 5000:5000 test:latest

  verify_deploy:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: deploy_docker 

    steps:
    - name: Verify Deployment
      uses: peterkimzz/aws-ssm-send-command@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
          if [ "$STATUS" -eq 200 ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
            exit 1
          fi

